name: Clippy
on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Clippy main library
      run: cargo clippy

    - name: Clippy tests
      run: cargo clippy --tests
