[package]
name = "smartcast"
version = "0.1.0"
description = "API to connect to Vizio SmartCast devices"
repository = "https://github.com/ConnorTroy/smartcast"
readme = "README.md"
authors = ["Connor Troy <connor.troy@tuta.io>"]
edition = "2018"

[dependencies]
reqwest = {version = "0.11.4", features = ["native-tls"] }
httparse = "1.4.1"
regex = "1.5.4"
serde_json = "1.0.64"
