[package]
name = "smartcast"
version = "0.1.0"
authors = ["Connor Troy <connor.troy@tuta.io>"]
edition = "2018"

[dependencies]
httparse = "1.4.1"
reqwest = "0.11.3"
regex = "1.5.4"
serde_json = "1.0.64"
