name: Build
on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:

  clippy:

    name: Clippy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clippy main library
      run: cargo clippy -- -D warnings

    - name: Clippy tests
      run: cargo clippy --tests -- -D warnings


  style:

    name: Check Style
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cargo fmt check
      run: cargo fmt -- --check


  docs:

    name: Docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Doc check
      run: RUSTDOCFLAGS='-D warnings' cargo doc --no-deps --document-private-items --all-features


  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1


  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1


  mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1
